spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        validate-topic-input:
          destination: notification-topic
          group: notification-group
          content-type: application/json
  datasource:
    url: jdbc:mysql://localhost:3306/wukong?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: select 1
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  mail:
    host: smtp.qq.com
    username: 411742963@qq.com
    password: vnkzxfysfgdcbjcj
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/views/